export const INVITATION_TEMPLATES = [
  {
    key: "classic-wine",
    name: "Rượu vang cổ điển",
    description: "Thanh lịch, trang trọng và phù hợp tiệc cưới truyền thống.",
    style: "Cổ điển",
    category: "TRADITIONAL",
    plan: "FREE",
    badge: "Phổ biến",
    featured: true,
    isNew: false,
    tags: ["trang trọng", "truyền thống", "đỏ vang"],
    motif: "monogram",
    motion: "elegant",
    palette: { primaryColor: "#7C2D3B", accentColor: "#B28A4A", backgroundColor: "#FBF7F1", surfaceColor: "#FFFDF9", textColor: "#29231F" },
    headingFont: "elegant-serif",
    bodyFont: "clean-sans",
  },
  {
    key: "garden-sage",
    name: "Vườn xanh dịu dàng",
    description: "Tự nhiên, nhẹ nhàng với sắc xanh sage và kem ấm.",
    style: "Thiên nhiên",
    category: "BOTANICAL",
    plan: "FREE",
    badge: "Được yêu thích",
    featured: true,
    isNew: false,
    tags: ["ngoài trời", "xanh sage", "hoa lá"],
    motif: "leaf",
    motion: "soft",
    palette: { primaryColor: "#566B55", accentColor: "#A58354", backgroundColor: "#F4F5EF", surfaceColor: "#FFFEFA", textColor: "#263026" },
    headingFont: "romantic-serif",
    bodyFont: "clean-sans",
  },
  {
    key: "blush-romance",
    name: "Hồng phấn lãng mạn",
    description: "Mềm mại, ấm áp cho phong cách cưới hiện đại và tinh tế.",
    style: "Lãng mạn",
    category: "ROMANTIC",
    plan: "STARTER",
    badge: null,
    featured: true,
    isNew: false,
    tags: ["hồng phấn", "nhẹ nhàng", "lãng mạn"],
    motif: "petal",
    motion: "soft",
    palette: { primaryColor: "#A75D69", accentColor: "#C39978", backgroundColor: "#FFF5F3", surfaceColor: "#FFFCFB", textColor: "#352729" },
    headingFont: "romantic-serif",
    bodyFont: "clean-sans",
  },
  {
    key: "modern-noir",
    name: "Noir hiện đại",
    description: "Tương phản mạnh, tối giản và sang trọng cho tiệc tối.",
    style: "Hiện đại",
    category: "MODERN",
    plan: "STARTER",
    badge: "Sang trọng",
    featured: true,
    isNew: false,
    tags: ["đen", "tiệc tối", "editorial"],
    motif: "line",
    motion: "editorial",
    palette: { primaryColor: "#161616", accentColor: "#C5A46D", backgroundColor: "#EEECE8", surfaceColor: "#FFFFFF", textColor: "#171717" },
    headingFont: "editorial-serif",
    bodyFont: "modern-sans",
  },
  {
    key: "ocean-minimal",
    name: "Biển xanh tối giản",
    description: "Thoáng, sáng và hiện đại, phù hợp tiệc cưới bên biển.",
    style: "Tối giản",
    category: "MINIMAL",
    plan: "STARTER",
    badge: null,
    featured: true,
    isNew: false,
    tags: ["biển", "xanh", "tối giản"],
    motif: "wave",
    motion: "clean",
    palette: { primaryColor: "#315E6C", accentColor: "#C59A65", backgroundColor: "#F1F6F7", surfaceColor: "#FFFFFF", textColor: "#203238" },
    headingFont: "elegant-serif",
    bodyFont: "modern-sans",
  },
  {
    key: "lotus-vietnamese",
    name: "Sen Việt thanh nhã",
    description: "Hoa sen, sắc ngọc và bố cục trang trọng dành cho nghi lễ Việt.",
    style: "Á Đông",
    category: "VIETNAMESE",
    plan: "STARTER",
    badge: "Đậm chất Việt",
    featured: true,
    isNew: true,
    tags: ["hoa sen", "á đông", "nghi lễ"],
    motif: "lotus",
    motion: "ceremonial",
    palette: { primaryColor: "#315B4A", accentColor: "#C8A35F", backgroundColor: "#F8F1E4", surfaceColor: "#FFFDF8", textColor: "#22352D" },
    headingFont: "heritage-serif",
    bodyFont: "humanist-sans",
  },
  {
    key: "imperial-red",
    name: "Hỷ sắc cung đình",
    description: "Đỏ son và vàng kim, nổi bật cho lễ cưới truyền thống long trọng.",
    style: "Truyền thống",
    category: "VIETNAMESE",
    plan: "STARTER",
    badge: "Mới",
    featured: true,
    isNew: true,
    tags: ["đỏ son", "vàng kim", "cung đình"],
    motif: "double-happiness",
    motion: "ceremonial",
    palette: { primaryColor: "#9E1F2F", accentColor: "#D5AE58", backgroundColor: "#FFF4E7", surfaceColor: "#FFFDF8", textColor: "#3C1E1B" },
    headingFont: "heritage-serif",
    bodyFont: "humanist-sans",
  },
  {
    key: "ivory-gold",
    name: "Ngà và ánh kim",
    description: "Tông ngà tinh khiết kết hợp ánh kim cho tiệc cưới khách sạn.",
    style: "Luxury",
    category: "LUXURY",
    plan: "STARTER",
    badge: null,
    featured: true,
    isNew: false,
    tags: ["ngà", "vàng", "khách sạn"],
    motif: "arch",
    motion: "elegant",
    palette: { primaryColor: "#6E5840", accentColor: "#C8A96C", backgroundColor: "#FAF7F0", surfaceColor: "#FFFFFF", textColor: "#2F2922" },
    headingFont: "minimal-serif",
    bodyFont: "clean-sans",
  },
  {
    key: "lavender-dream",
    name: "Giấc mơ lavender",
    description: "Tím lavender dịu nhẹ, mơ màng và trẻ trung.",
    style: "Lãng mạn",
    category: "ROMANTIC",
    plan: "STANDARD",
    badge: null,
    featured: false,
    isNew: false,
    tags: ["lavender", "tím", "mơ màng"],
    motif: "flower",
    motion: "soft",
    palette: { primaryColor: "#78678C", accentColor: "#C4A2B8", backgroundColor: "#F7F3FA", surfaceColor: "#FFFFFF", textColor: "#302A36" },
    headingFont: "romantic-serif",
    bodyFont: "soft-sans",
  },
  {
    key: "terracotta-sunset",
    name: "Hoàng hôn đất nung",
    description: "Ấm áp, tự do và giàu cảm xúc cho đám cưới ngoài trời.",
    style: "Bohemian",
    category: "BOTANICAL",
    plan: "STANDARD",
    badge: "Outdoor",
    featured: false,
    isNew: false,
    tags: ["terracotta", "boho", "ngoài trời"],
    motif: "sun",
    motion: "organic",
    palette: { primaryColor: "#A65137", accentColor: "#D59A62", backgroundColor: "#FBF1E8", surfaceColor: "#FFFDF9", textColor: "#412D27" },
    headingFont: "elegant-serif",
    bodyFont: "humanist-sans",
  },
  {
    key: "pearl-minimal",
    name: "Ngọc trai tối giản",
    description: "Khoảng trắng rộng, tinh tế và hiện đại cho cặp đôi yêu sự gọn gàng.",
    style: "Tối giản",
    category: "MINIMAL",
    plan: "STANDARD",
    badge: null,
    featured: false,
    isNew: false,
    tags: ["trắng", "tối giản", "ngọc trai"],
    motif: "pearl",
    motion: "clean",
    palette: { primaryColor: "#474B4C", accentColor: "#B7A790", backgroundColor: "#F7F7F5", surfaceColor: "#FFFFFF", textColor: "#26292A" },
    headingFont: "minimal-serif",
    bodyFont: "modern-sans",
  },
  {
    key: "midnight-blue",
    name: "Dạ lam ánh sao",
    description: "Xanh đêm sâu, ánh vàng tinh tế cho buổi tiệc tối lãng mạn.",
    style: "Tiệc tối",
    category: "LUXURY",
    plan: "STANDARD",
    badge: "Tiệc tối",
    featured: false,
    isNew: false,
    tags: ["xanh đêm", "ánh sao", "tiệc tối"],
    motif: "star",
    motion: "celestial",
    palette: { primaryColor: "#172A46", accentColor: "#D7B56D", backgroundColor: "#EDF1F7", surfaceColor: "#FFFFFF", textColor: "#172238" },
    headingFont: "editorial-serif",
    bodyFont: "clean-sans",
  },
  {
    key: "tropical-palm",
    name: "Nhiệt đới xanh mát",
    description: "Lá cọ và xanh ngọc cho destination wedding đầy năng lượng.",
    style: "Nhiệt đới",
    category: "DESTINATION",
    plan: "STANDARD",
    badge: null,
    featured: false,
    isNew: true,
    tags: ["lá cọ", "destination", "nhiệt đới"],
    motif: "palm",
    motion: "organic",
    palette: { primaryColor: "#176B5C", accentColor: "#E0A85A", backgroundColor: "#EFF8F4", surfaceColor: "#FFFFFF", textColor: "#18352F" },
    headingFont: "elegant-serif",
    bodyFont: "humanist-sans",
  },
  {
    key: "cherry-blossom",
    name: "Anh đào ban mai",
    description: "Sắc hồng trong trẻo và nét Á Đông nhẹ nhàng.",
    style: "Á Đông",
    category: "ROMANTIC",
    plan: "STANDARD",
    badge: "Mới",
    featured: false,
    isNew: true,
    tags: ["anh đào", "hồng", "á đông"],
    motif: "blossom",
    motion: "soft",
    palette: { primaryColor: "#92566A", accentColor: "#D7A0A9", backgroundColor: "#FFF7F8", surfaceColor: "#FFFFFF", textColor: "#3D2B32" },
    headingFont: "romantic-serif",
    bodyFont: "soft-sans",
  },
  {
    key: "rustic-kraft",
    name: "Mộc mạc kraft",
    description: "Chất liệu giấy kraft, màu đất và cảm giác gần gũi.",
    style: "Rustic",
    category: "BOTANICAL",
    plan: "STANDARD",
    badge: null,
    featured: false,
    isNew: false,
    tags: ["kraft", "mộc mạc", "vintage"],
    motif: "branch",
    motion: "organic",
    palette: { primaryColor: "#6B4F36", accentColor: "#9C7A4E", backgroundColor: "#F1E5D3", surfaceColor: "#FFF9EF", textColor: "#3B2F25" },
    headingFont: "heritage-serif",
    bodyFont: "humanist-sans",
  },
  {
    key: "art-deco-emerald",
    name: "Emerald Art Deco",
    description: "Hình học Art Deco, xanh emerald và ánh kim đầy cá tính.",
    style: "Art Deco",
    category: "LUXURY",
    plan: "STANDARD",
    badge: "Premium look",
    featured: false,
    isNew: false,
    tags: ["art deco", "emerald", "hình học"],
    motif: "deco",
    motion: "editorial",
    palette: { primaryColor: "#0F5448", accentColor: "#D2B46C", backgroundColor: "#F1F5F0", surfaceColor: "#FFFFFF", textColor: "#15332D" },
    headingFont: "display-serif",
    bodyFont: "modern-sans",
  },
  {
    key: "champagne-glow",
    name: "Champagne rạng rỡ",
    description: "Ánh champagne mềm mại, trang nhã và phù hợp nhiều không gian.",
    style: "Luxury",
    category: "LUXURY",
    plan: "PREMIUM",
    badge: null,
    featured: false,
    isNew: false,
    tags: ["champagne", "ánh kim", "thanh lịch"],
    motif: "sparkle",
    motion: "elegant",
    palette: { primaryColor: "#806A53", accentColor: "#D8B884", backgroundColor: "#FBF5E9", surfaceColor: "#FFFDF9", textColor: "#352E27" },
    headingFont: "minimal-serif",
    bodyFont: "clean-sans",
  },
  {
    key: "celestial-night",
    name: "Thiên hà đêm cưới",
    description: "Bầu trời sao và sắc tím đêm cho một câu chuyện kỳ diệu.",
    style: "Fantasy",
    category: "MODERN",
    plan: "PREMIUM",
    badge: "Animation",
    featured: false,
    isNew: true,
    tags: ["thiên hà", "tím đêm", "ánh sao"],
    motif: "moon",
    motion: "celestial",
    palette: { primaryColor: "#312A59", accentColor: "#D6B6EA", backgroundColor: "#F2EFFA", surfaceColor: "#FFFFFF", textColor: "#24213B" },
    headingFont: "display-serif",
    bodyFont: "soft-sans",
  },
  {
    key: "coastal-sand",
    name: "Cát biển an nhiên",
    description: "Be cát, xanh biển nhạt và bố cục thoáng cho lễ cưới ven biển.",
    style: "Biển",
    category: "DESTINATION",
    plan: "PREMIUM",
    badge: null,
    featured: false,
    isNew: false,
    tags: ["cát biển", "destination", "be"],
    motif: "shell",
    motion: "clean",
    palette: { primaryColor: "#52767B", accentColor: "#C9A879", backgroundColor: "#F8F3EA", surfaceColor: "#FFFFFF", textColor: "#2E3F40" },
    headingFont: "minimal-serif",
    bodyFont: "humanist-sans",
  },
  {
    key: "tea-ceremony",
    name: "Trà lễ sum vầy",
    description: "Sắc trà, gỗ ấm và hoa văn tinh tế cho lễ gia tiên.",
    style: "Nghi lễ",
    category: "VIETNAMESE",
    plan: "PREMIUM",
    badge: "Nghi lễ Việt",
    featured: false,
    isNew: true,
    tags: ["trà lễ", "gia tiên", "gỗ ấm"],
    motif: "tea",
    motion: "ceremonial",
    palette: { primaryColor: "#6F3F2F", accentColor: "#C79552", backgroundColor: "#FAF0E1", surfaceColor: "#FFF9F0", textColor: "#38261F" },
    headingFont: "heritage-serif",
    bodyFont: "humanist-sans",
  },
  {
    key: "monochrome-editorial",
    name: "Editorial đơn sắc",
    description: "Đen trắng thời thượng, typography lớn và bố cục như tạp chí.",
    style: "Editorial",
    category: "MODERN",
    plan: "PREMIUM",
    badge: null,
    featured: false,
    isNew: false,
    tags: ["đen trắng", "editorial", "fashion"],
    motif: "type",
    motion: "editorial",
    palette: { primaryColor: "#101010", accentColor: "#8E8E8E", backgroundColor: "#F4F4F2", surfaceColor: "#FFFFFF", textColor: "#101010" },
    headingFont: "display-serif",
    bodyFont: "modern-sans",
  },
  {
    key: "peach-bloom",
    name: "Đào nở dịu êm",
    description: "Cam đào sáng, trẻ trung và ấm áp cho lễ cưới thân mật.",
    style: "Trẻ trung",
    category: "ROMANTIC",
    plan: "PREMIUM",
    badge: null,
    featured: false,
    isNew: true,
    tags: ["cam đào", "trẻ trung", "ấm áp"],
    motif: "peach",
    motion: "soft",
    palette: { primaryColor: "#B96455", accentColor: "#E4A57E", backgroundColor: "#FFF4EC", surfaceColor: "#FFFFFF", textColor: "#442D29" },
    headingFont: "romantic-serif",
    bodyFont: "soft-sans",
  },
  {
    key: "heritage-indigo",
    name: "Chàm Việt di sản",
    description: "Sắc chàm, họa tiết thủ công và tinh thần di sản Việt Nam.",
    style: "Di sản",
    category: "VIETNAMESE",
    plan: "PREMIUM",
    badge: "Độc quyền",
    featured: false,
    isNew: true,
    tags: ["chàm", "di sản", "thủ công"],
    motif: "indigo",
    motion: "ceremonial",
    palette: { primaryColor: "#294A66", accentColor: "#C9A45C", backgroundColor: "#F2F0E8", surfaceColor: "#FFFDF8", textColor: "#24313A" },
    headingFont: "heritage-serif",
    bodyFont: "humanist-sans",
  },
  {
    key: "botanical-white",
    name: "Botanical trắng xanh",
    description: "Hoa lá nét mảnh trên nền trắng, tinh khiết và thanh lịch.",
    style: "Botanical",
    category: "BOTANICAL",
    plan: "PREMIUM",
    badge: null,
    featured: false,
    isNew: false,
    tags: ["botanical", "trắng xanh", "hoa lá"],
    motif: "botanical",
    motion: "organic",
    palette: { primaryColor: "#4D6757", accentColor: "#A9A37E", backgroundColor: "#F8FAF7", surfaceColor: "#FFFFFF", textColor: "#29342D" },
    headingFont: "minimal-serif",
    bodyFont: "clean-sans",
  },
] as const;

export const INVITATION_TEMPLATE_KEYS = INVITATION_TEMPLATES.map((template) => template.key);
export const INVITATION_TEMPLATE_KEY_SET = new Set<string>(INVITATION_TEMPLATE_KEYS);

export const DEFAULT_SECTION_ORDER = ["hero", "family", "story", "gallery", "countdown", "events", "footer"];
export const VALID_SECTION_KEYS = new Set(DEFAULT_SECTION_ORDER);
export const VALID_FONT_KEYS = new Set(["elegant-serif", "romantic-serif", "editorial-serif", "heritage-serif", "minimal-serif", "display-serif", "clean-sans", "modern-sans", "humanist-sans", "soft-sans"]);
