const BASE_INVITATION_TEMPLATES = [
  {
    key: "classic-wine",
    name: "Rượu vang cổ điển",
    description: "Thanh lịch, trang trọng và phù hợp tiệc cưới truyền thống.",
    style: "Cổ điển",
    category: "TRADITIONAL",
    plan: "FREE",
    badge: "Phổ biến",
    featured: true,
    isNew: false,
    tags: ["trang trọng", "truyền thống", "đỏ vang"],
    motif: "monogram",
    motion: "elegant",
    palette: { primaryColor: "#7C2D3B", accentColor: "#B28A4A", backgroundColor: "#FBF7F1", surfaceColor: "#FFFDF9", textColor: "#29231F" },
    headingFont: "elegant-serif",
    bodyFont: "clean-sans",
  },
  {
    key: "garden-sage",
    name: "Vườn xanh dịu dàng",
    description: "Tự nhiên, nhẹ nhàng với sắc xanh sage và kem ấm.",
    style: "Thiên nhiên",
    category: "BOTANICAL",
    plan: "FREE",
    badge: "Được yêu thích",
    featured: true,
    isNew: false,
    tags: ["ngoài trời", "xanh sage", "hoa lá"],
    motif: "leaf",
    motion: "soft",
    palette: { primaryColor: "#566B55", accentColor: "#A58354", backgroundColor: "#F4F5EF", surfaceColor: "#FFFEFA", textColor: "#263026" },
    headingFont: "romantic-serif",
    bodyFont: "clean-sans",
  },
  {
    key: "blush-romance",
    name: "Hồng phấn lãng mạn",
    description: "Mềm mại, ấm áp cho phong cách cưới hiện đại và tinh tế.",
    style: "Lãng mạn",
    category: "ROMANTIC",
    plan: "STARTER",
    badge: null,
    featured: true,
    isNew: false,
    tags: ["hồng phấn", "nhẹ nhàng", "lãng mạn"],
    motif: "petal",
    motion: "soft",
    palette: { primaryColor: "#A75D69", accentColor: "#C39978", backgroundColor: "#FFF5F3", surfaceColor: "#FFFCFB", textColor: "#352729" },
    headingFont: "romantic-serif",
    bodyFont: "clean-sans",
  },
  {
    key: "modern-noir",
    name: "Noir hiện đại",
    description: "Tương phản mạnh, tối giản và sang trọng cho tiệc tối.",
    style: "Hiện đại",
    category: "MODERN",
    plan: "STARTER",
    badge: "Sang trọng",
    featured: true,
    isNew: false,
    tags: ["đen", "tiệc tối", "editorial"],
    motif: "line",
    motion: "editorial",
    palette: { primaryColor: "#161616", accentColor: "#C5A46D", backgroundColor: "#EEECE8", surfaceColor: "#FFFFFF", textColor: "#171717" },
    headingFont: "editorial-serif",
    bodyFont: "modern-sans",
  },
  {
    key: "ocean-minimal",
    name: "Biển xanh tối giản",
    description: "Thoáng, sáng và hiện đại, phù hợp tiệc cưới bên biển.",
    style: "Tối giản",
    category: "MINIMAL",
    plan: "STARTER",
    badge: null,
    featured: true,
    isNew: false,
    tags: ["biển", "xanh", "tối giản"],
    motif: "wave",
    motion: "clean",
    palette: { primaryColor: "#315E6C", accentColor: "#C59A65", backgroundColor: "#F1F6F7", surfaceColor: "#FFFFFF", textColor: "#203238" },
    headingFont: "elegant-serif",
    bodyFont: "modern-sans",
  },
  {
    key: "lotus-vietnamese",
    name: "Sen Việt thanh nhã",
    description: "Hoa sen, sắc ngọc và bố cục trang trọng dành cho nghi lễ Việt.",
    style: "Á Đông",
    category: "VIETNAMESE",
    plan: "STARTER",
    badge: "Đậm chất Việt",
    featured: true,
    isNew: true,
    tags: ["hoa sen", "á đông", "nghi lễ"],
    motif: "lotus",
    motion: "ceremonial",
    palette: { primaryColor: "#315B4A", accentColor: "#C8A35F", backgroundColor: "#F8F1E4", surfaceColor: "#FFFDF8", textColor: "#22352D" },
    headingFont: "heritage-serif",
    bodyFont: "humanist-sans",
  },
  {
    key: "imperial-red",
    name: "Hỷ sắc cung đình",
    description: "Đỏ son và vàng kim, nổi bật cho lễ cưới truyền thống long trọng.",
    style: "Truyền thống",
    category: "VIETNAMESE",
    plan: "STARTER",
    badge: "Mới",
    featured: true,
    isNew: true,
    tags: ["đỏ son", "vàng kim", "cung đình"],
    motif: "double-happiness",
    motion: "ceremonial",
    palette: { primaryColor: "#9E1F2F", accentColor: "#D5AE58", backgroundColor: "#FFF4E7", surfaceColor: "#FFFDF8", textColor: "#3C1E1B" },
    headingFont: "heritage-serif",
    bodyFont: "humanist-sans",
  },
  {
    key: "ivory-gold",
    name: "Ngà và ánh kim",
    description: "Tông ngà tinh khiết kết hợp ánh kim cho tiệc cưới khách sạn.",
    style: "Luxury",
    category: "LUXURY",
    plan: "STARTER",
    badge: null,
    featured: true,
    isNew: false,
    tags: ["ngà", "vàng", "khách sạn"],
    motif: "arch",
    motion: "elegant",
    palette: { primaryColor: "#6E5840", accentColor: "#C8A96C", backgroundColor: "#FAF7F0", surfaceColor: "#FFFFFF", textColor: "#2F2922" },
    headingFont: "minimal-serif",
    bodyFont: "clean-sans",
  },
  {
    key: "lavender-dream",
    name: "Giấc mơ lavender",
    description: "Tím lavender dịu nhẹ, mơ màng và trẻ trung.",
    style: "Lãng mạn",
    category: "ROMANTIC",
    plan: "STANDARD",
    badge: null,
    featured: false,
    isNew: false,
    tags: ["lavender", "tím", "mơ màng"],
    motif: "flower",
    motion: "soft",
    palette: { primaryColor: "#78678C", accentColor: "#C4A2B8", backgroundColor: "#F7F3FA", surfaceColor: "#FFFFFF", textColor: "#302A36" },
    headingFont: "romantic-serif",
    bodyFont: "soft-sans",
  },
  {
    key: "terracotta-sunset",
    name: "Hoàng hôn đất nung",
    description: "Ấm áp, tự do và giàu cảm xúc cho đám cưới ngoài trời.",
    style: "Bohemian",
    category: "BOTANICAL",
    plan: "STANDARD",
    badge: "Outdoor",
    featured: false,
    isNew: false,
    tags: ["terracotta", "boho", "ngoài trời"],
    motif: "sun",
    motion: "organic",
    palette: { primaryColor: "#A65137", accentColor: "#D59A62", backgroundColor: "#FBF1E8", surfaceColor: "#FFFDF9", textColor: "#412D27" },
    headingFont: "elegant-serif",
    bodyFont: "humanist-sans",
  },
  {
    key: "pearl-minimal",
    name: "Ngọc trai tối giản",
    description: "Khoảng trắng rộng, tinh tế và hiện đại cho cặp đôi yêu sự gọn gàng.",
    style: "Tối giản",
    category: "MINIMAL",
    plan: "STANDARD",
    badge: null,
    featured: false,
    isNew: false,
    tags: ["trắng", "tối giản", "ngọc trai"],
    motif: "pearl",
    motion: "clean",
    palette: { primaryColor: "#474B4C", accentColor: "#B7A790", backgroundColor: "#F7F7F5", surfaceColor: "#FFFFFF", textColor: "#26292A" },
    headingFont: "minimal-serif",
    bodyFont: "modern-sans",
  },
  {
    key: "midnight-blue",
    name: "Dạ lam ánh sao",
    description: "Xanh đêm sâu, ánh vàng tinh tế cho buổi tiệc tối lãng mạn.",
    style: "Tiệc tối",
    category: "LUXURY",
    plan: "STANDARD",
    badge: "Tiệc tối",
    featured: false,
    isNew: false,
    tags: ["xanh đêm", "ánh sao", "tiệc tối"],
    motif: "star",
    motion: "celestial",
    palette: { primaryColor: "#172A46", accentColor: "#D7B56D", backgroundColor: "#EDF1F7", surfaceColor: "#FFFFFF", textColor: "#172238" },
    headingFont: "editorial-serif",
    bodyFont: "clean-sans",
  },
  {
    key: "tropical-palm",
    name: "Nhiệt đới xanh mát",
    description: "Lá cọ và xanh ngọc cho destination wedding đầy năng lượng.",
    style: "Nhiệt đới",
    category: "DESTINATION",
    plan: "STANDARD",
    badge: null,
    featured: false,
    isNew: true,
    tags: ["lá cọ", "destination", "nhiệt đới"],
    motif: "palm",
    motion: "organic",
    palette: { primaryColor: "#176B5C", accentColor: "#E0A85A", backgroundColor: "#EFF8F4", surfaceColor: "#FFFFFF", textColor: "#18352F" },
    headingFont: "elegant-serif",
    bodyFont: "humanist-sans",
  },
  {
    key: "cherry-blossom",
    name: "Anh đào ban mai",
    description: "Sắc hồng trong trẻo và nét Á Đông nhẹ nhàng.",
    style: "Á Đông",
    category: "ROMANTIC",
    plan: "STANDARD",
    badge: "Mới",
    featured: false,
    isNew: true,
    tags: ["anh đào", "hồng", "á đông"],
    motif: "blossom",
    motion: "soft",
    palette: { primaryColor: "#92566A", accentColor: "#D7A0A9", backgroundColor: "#FFF7F8", surfaceColor: "#FFFFFF", textColor: "#3D2B32" },
    headingFont: "romantic-serif",
    bodyFont: "soft-sans",
  },
  {
    key: "rustic-kraft",
    name: "Mộc mạc kraft",
    description: "Chất liệu giấy kraft, màu đất và cảm giác gần gũi.",
    style: "Rustic",
    category: "BOTANICAL",
    plan: "STANDARD",
    badge: null,
    featured: false,
    isNew: false,
    tags: ["kraft", "mộc mạc", "vintage"],
    motif: "branch",
    motion: "organic",
    palette: { primaryColor: "#6B4F36", accentColor: "#9C7A4E", backgroundColor: "#F1E5D3", surfaceColor: "#FFF9EF", textColor: "#3B2F25" },
    headingFont: "heritage-serif",
    bodyFont: "humanist-sans",
  },
  {
    key: "art-deco-emerald",
    name: "Emerald Art Deco",
    description: "Hình học Art Deco, xanh emerald và ánh kim đầy cá tính.",
    style: "Art Deco",
    category: "LUXURY",
    plan: "STANDARD",
    badge: "Premium look",
    featured: false,
    isNew: false,
    tags: ["art deco", "emerald", "hình học"],
    motif: "deco",
    motion: "editorial",
    palette: { primaryColor: "#0F5448", accentColor: "#D2B46C", backgroundColor: "#F1F5F0", surfaceColor: "#FFFFFF", textColor: "#15332D" },
    headingFont: "display-serif",
    bodyFont: "modern-sans",
  },
  {
    key: "champagne-glow",
    name: "Champagne rạng rỡ",
    description: "Ánh champagne mềm mại, trang nhã và phù hợp nhiều không gian.",
    style: "Luxury",
    category: "LUXURY",
    plan: "PREMIUM",
    badge: null,
    featured: false,
    isNew: false,
    tags: ["champagne", "ánh kim", "thanh lịch"],
    motif: "sparkle",
    motion: "elegant",
    palette: { primaryColor: "#806A53", accentColor: "#D8B884", backgroundColor: "#FBF5E9", surfaceColor: "#FFFDF9", textColor: "#352E27" },
    headingFont: "minimal-serif",
    bodyFont: "clean-sans",
  },
  {
    key: "celestial-night",
    name: "Thiên hà đêm cưới",
    description: "Bầu trời sao và sắc tím đêm cho một câu chuyện kỳ diệu.",
    style: "Fantasy",
    category: "MODERN",
    plan: "PREMIUM",
    badge: "Animation",
    featured: false,
    isNew: true,
    tags: ["thiên hà", "tím đêm", "ánh sao"],
    motif: "moon",
    motion: "celestial",
    palette: { primaryColor: "#312A59", accentColor: "#D6B6EA", backgroundColor: "#F2EFFA", surfaceColor: "#FFFFFF", textColor: "#24213B" },
    headingFont: "display-serif",
    bodyFont: "soft-sans",
  },
  {
    key: "coastal-sand",
    name: "Cát biển an nhiên",
    description: "Be cát, xanh biển nhạt và bố cục thoáng cho lễ cưới ven biển.",
    style: "Biển",
    category: "DESTINATION",
    plan: "PREMIUM",
    badge: null,
    featured: false,
    isNew: false,
    tags: ["cát biển", "destination", "be"],
    motif: "shell",
    motion: "clean",
    palette: { primaryColor: "#52767B", accentColor: "#C9A879", backgroundColor: "#F8F3EA", surfaceColor: "#FFFFFF", textColor: "#2E3F40" },
    headingFont: "minimal-serif",
    bodyFont: "humanist-sans",
  },
  {
    key: "tea-ceremony",
    name: "Trà lễ sum vầy",
    description: "Sắc trà, gỗ ấm và hoa văn tinh tế cho lễ gia tiên.",
    style: "Nghi lễ",
    category: "VIETNAMESE",
    plan: "PREMIUM",
    badge: "Nghi lễ Việt",
    featured: false,
    isNew: true,
    tags: ["trà lễ", "gia tiên", "gỗ ấm"],
    motif: "tea",
    motion: "ceremonial",
    palette: { primaryColor: "#6F3F2F", accentColor: "#C79552", backgroundColor: "#FAF0E1", surfaceColor: "#FFF9F0", textColor: "#38261F" },
    headingFont: "heritage-serif",
    bodyFont: "humanist-sans",
  },
  {
    key: "monochrome-editorial",
    name: "Editorial đơn sắc",
    description: "Đen trắng thời thượng, typography lớn và bố cục như tạp chí.",
    style: "Editorial",
    category: "MODERN",
    plan: "PREMIUM",
    badge: null,
    featured: false,
    isNew: false,
    tags: ["đen trắng", "editorial", "fashion"],
    motif: "type",
    motion: "editorial",
    palette: { primaryColor: "#101010", accentColor: "#8E8E8E", backgroundColor: "#F4F4F2", surfaceColor: "#FFFFFF", textColor: "#101010" },
    headingFont: "display-serif",
    bodyFont: "modern-sans",
  },
  {
    key: "peach-bloom",
    name: "Đào nở dịu êm",
    description: "Cam đào sáng, trẻ trung và ấm áp cho lễ cưới thân mật.",
    style: "Trẻ trung",
    category: "ROMANTIC",
    plan: "PREMIUM",
    badge: null,
    featured: false,
    isNew: true,
    tags: ["cam đào", "trẻ trung", "ấm áp"],
    motif: "peach",
    motion: "soft",
    palette: { primaryColor: "#B96455", accentColor: "#E4A57E", backgroundColor: "#FFF4EC", surfaceColor: "#FFFFFF", textColor: "#442D29" },
    headingFont: "romantic-serif",
    bodyFont: "soft-sans",
  },
  {
    key: "heritage-indigo",
    name: "Chàm Việt di sản",
    description: "Sắc chàm, họa tiết thủ công và tinh thần di sản Việt Nam.",
    style: "Di sản",
    category: "VIETNAMESE",
    plan: "PREMIUM",
    badge: "Độc quyền",
    featured: false,
    isNew: true,
    tags: ["chàm", "di sản", "thủ công"],
    motif: "indigo",
    motion: "ceremonial",
    palette: { primaryColor: "#294A66", accentColor: "#C9A45C", backgroundColor: "#F2F0E8", surfaceColor: "#FFFDF8", textColor: "#24313A" },
    headingFont: "heritage-serif",
    bodyFont: "humanist-sans",
  },
  {
    key: "botanical-white",
    name: "Botanical trắng xanh",
    description: "Hoa lá nét mảnh trên nền trắng, tinh khiết và thanh lịch.",
    style: "Botanical",
    category: "BOTANICAL",
    plan: "PREMIUM",
    badge: null,
    featured: false,
    isNew: false,
    tags: ["botanical", "trắng xanh", "hoa lá"],
    motif: "botanical",
    motion: "organic",
    palette: { primaryColor: "#4D6757", accentColor: "#A9A37E", backgroundColor: "#F8FAF7", surfaceColor: "#FFFFFF", textColor: "#29342D" },
    headingFont: "minimal-serif",
    bodyFont: "clean-sans",
  },
  {
    key: "saigon-sunrise",
    name: "Sài Gòn sớm mai",
    description: "Nhịp đô thị thanh lịch, typography lớn và ảnh cưới điện ảnh.",
    style: "Urban editorial",
    category: "MODERN",
    plan: "STARTER",
    badge: "Mới",
    featured: true,
    isNew: true,
    tags: ["sài gòn", "editorial", "đô thị"],
    motif: "city-line",
    motion: "editorial",
    palette: { primaryColor: "#713E35", accentColor: "#E1A366", backgroundColor: "#FFF6EC", surfaceColor: "#FFFFFF", textColor: "#302522" },
    headingFont: "display-serif",
    bodyFont: "modern-sans",
  },
  {
    key: "polaroid-memories",
    name: "Polaroid ngày mình",
    description: "Album ảnh kể chuyện như những tấm film được lưu qua năm tháng.",
    style: "Photo story",
    category: "ROMANTIC",
    plan: "STARTER",
    badge: "Nhiều ảnh",
    featured: true,
    isNew: true,
    tags: ["polaroid", "photo story", "kỷ niệm"],
    motif: "film",
    motion: "soft",
    palette: { primaryColor: "#7B5B4B", accentColor: "#D59C78", backgroundColor: "#F8EEE2", surfaceColor: "#FFFDF9", textColor: "#382B25" },
    headingFont: "romantic-serif",
    bodyFont: "humanist-sans",
  },
  {
    key: "han-river-blue",
    name: "Sông Hàn xanh",
    description: "Sắc lam hiện đại, ảnh chia đôi và khoảng thở phù hợp tiệc thành phố.",
    style: "City blue",
    category: "MINIMAL",
    plan: "STARTER",
    badge: null,
    featured: false,
    isNew: true,
    tags: ["đà nẵng", "xanh lam", "ảnh chia đôi"],
    motif: "bridge",
    motion: "clean",
    palette: { primaryColor: "#25556A", accentColor: "#C5A169", backgroundColor: "#EFF7FA", surfaceColor: "#FFFFFF", textColor: "#20343D" },
    headingFont: "minimal-serif",
    bodyFont: "clean-sans",
  },
  {
    key: "rose-garden-frame",
    name: "Khung vườn hồng",
    description: "Khung vòm hoa hồng mềm mại, phù hợp lễ cưới sân vườn.",
    style: "Garden romance",
    category: "BOTANICAL",
    plan: "STARTER",
    badge: "Garden",
    featured: true,
    isNew: true,
    tags: ["hoa hồng", "khung vòm", "sân vườn"],
    motif: "rose-arch",
    motion: "organic",
    palette: { primaryColor: "#81505A", accentColor: "#CDA188", backgroundColor: "#FFF5F3", surfaceColor: "#FFFFFF", textColor: "#3C2B30" },
    headingFont: "romantic-serif",
    bodyFont: "soft-sans",
  },
  {
    key: "cinematic-veil",
    name: "Voan cưới điện ảnh",
    description: "Ảnh chân dung toàn màn hình, ánh sáng mềm và cảm giác như poster phim.",
    style: "Cinematic",
    category: "LUXURY",
    plan: "STANDARD",
    badge: "Cinematic",
    featured: true,
    isNew: true,
    tags: ["điện ảnh", "ảnh lớn", "voan cưới"],
    motif: "veil",
    motion: "elegant",
    palette: { primaryColor: "#40363B", accentColor: "#D0B08C", backgroundColor: "#F5F0ED", surfaceColor: "#FFFFFF", textColor: "#2C272A" },
    headingFont: "editorial-serif",
    bodyFont: "clean-sans",
  },
  {
    key: "provence-blue",
    name: "Provence xanh tím",
    description: "Photo story mang sắc lavender và xanh Pháp cho tiệc ngoài trời.",
    style: "French garden",
    category: "BOTANICAL",
    plan: "STANDARD",
    badge: "Ảnh kể chuyện",
    featured: false,
    isNew: true,
    tags: ["provence", "lavender", "photo story"],
    motif: "lavender-stem",
    motion: "soft",
    palette: { primaryColor: "#626A8F", accentColor: "#B89BB7", backgroundColor: "#F5F3FA", surfaceColor: "#FFFFFF", textColor: "#303248" },
    headingFont: "romantic-serif",
    bodyFont: "soft-sans",
  },
  {
    key: "newspaper-love",
    name: "Bản tin ngày yêu",
    description: "Bố cục báo chí hiện đại, tên cặp đôi và câu chuyện là tâm điểm.",
    style: "Newspaper",
    category: "MODERN",
    plan: "STANDARD",
    badge: "Typography",
    featured: false,
    isNew: true,
    tags: ["newspaper", "typography", "editorial"],
    motif: "headline",
    motion: "editorial",
    palette: { primaryColor: "#24201D", accentColor: "#9C6D4C", backgroundColor: "#F4EFE7", surfaceColor: "#FFFDF8", textColor: "#211E1B" },
    headingFont: "display-serif",
    bodyFont: "modern-sans",
  },
  {
    key: "sunset-film",
    name: "Thước phim hoàng hôn",
    description: "Ảnh chia đôi màu film ấm, phù hợp tiệc biển và destination wedding.",
    style: "Film sunset",
    category: "DESTINATION",
    plan: "STANDARD",
    badge: "Destination",
    featured: false,
    isNew: true,
    tags: ["film", "hoàng hôn", "destination"],
    motif: "film-strip",
    motion: "organic",
    palette: { primaryColor: "#8D4E3C", accentColor: "#E0A36E", backgroundColor: "#FFF1E5", surfaceColor: "#FFFFFF", textColor: "#3E2A24" },
    headingFont: "elegant-serif",
    bodyFont: "humanist-sans",
  },
  {
    key: "dragon-phoenix",
    name: "Long phụng giao duyên",
    description: "Họa tiết nghi lễ Việt, khung vòm son kim và chương trình trang trọng.",
    style: "Lễ Việt cao cấp",
    category: "VIETNAMESE",
    plan: "PREMIUM",
    badge: "Di sản mới",
    featured: true,
    isNew: true,
    tags: ["long phụng", "lễ Việt", "son kim"],
    motif: "dragon-phoenix",
    motion: "ceremonial",
    palette: { primaryColor: "#8B1728", accentColor: "#D8B15F", backgroundColor: "#FFF2DF", surfaceColor: "#FFFDF8", textColor: "#3B1C1B" },
    headingFont: "heritage-serif",
    bodyFont: "humanist-sans",
  },
  {
    key: "museum-ivory",
    name: "Bảo tàng ngà",
    description: "Tối giản như một triển lãm nghệ thuật, tập trung vào ảnh và khoảng trắng.",
    style: "Gallery minimal",
    category: "MINIMAL",
    plan: "PREMIUM",
    badge: "Art direction",
    featured: false,
    isNew: true,
    tags: ["gallery", "tối giản", "ngà"],
    motif: "museum-label",
    motion: "clean",
    palette: { primaryColor: "#3E3B37", accentColor: "#B4A487", backgroundColor: "#F5F2EA", surfaceColor: "#FFFFFF", textColor: "#242321" },
    headingFont: "minimal-serif",
    bodyFont: "modern-sans",
  },
  {
    key: "winter-silver",
    name: "Mùa đông ánh bạc",
    description: "Ánh bạc, xanh khói và ảnh chân dung trang nhã cho tiệc cuối năm.",
    style: "Winter luxury",
    category: "LUXURY",
    plan: "PREMIUM",
    badge: "Winter",
    featured: false,
    isNew: true,
    tags: ["mùa đông", "ánh bạc", "tiệc tối"],
    motif: "snow-crystal",
    motion: "celestial",
    palette: { primaryColor: "#405166", accentColor: "#BFC7CF", backgroundColor: "#EFF3F7", surfaceColor: "#FFFFFF", textColor: "#27313D" },
    headingFont: "editorial-serif",
    bodyFont: "clean-sans",
  },
  {
    key: "cottage-floral",
    name: "Nhà hoa đồng nội",
    description: "Collage ảnh và hoa đồng nội mang cảm giác thân mật, ấm áp.",
    style: "Cottage floral",
    category: "BOTANICAL",
    plan: "PREMIUM",
    badge: "Handmade look",
    featured: false,
    isNew: true,
    tags: ["cottage", "hoa đồng nội", "collage"],
    motif: "wildflower",
    motion: "organic",
    palette: { primaryColor: "#5F6E50", accentColor: "#C9976B", backgroundColor: "#F8F3E8", surfaceColor: "#FFFDF8", textColor: "#30372A" },
    headingFont: "romantic-serif",
    bodyFont: "humanist-sans",
  },
] as const;

type TemplateExperience = {
  layout: "portrait" | "split" | "editorial" | "arch" | "story" | "minimal";
  photoTreatment: "full-bleed" | "split" | "framed" | "collage" | "soft" | "optional";
  countdownStyle: "cards" | "editorial" | "rings" | "minimal";
  eventStyle: "timeline" | "cards" | "agenda" | "steps";
};

const TEMPLATE_EXPERIENCE: Record<string, TemplateExperience> = {
  "classic-wine": { layout: "portrait", photoTreatment: "framed", countdownStyle: "cards", eventStyle: "timeline" },
  "garden-sage": { layout: "story", photoTreatment: "collage", countdownStyle: "rings", eventStyle: "cards" },
  "blush-romance": { layout: "split", photoTreatment: "split", countdownStyle: "cards", eventStyle: "timeline" },
  "modern-noir": { layout: "editorial", photoTreatment: "full-bleed", countdownStyle: "editorial", eventStyle: "agenda" },
  "ocean-minimal": { layout: "minimal", photoTreatment: "soft", countdownStyle: "minimal", eventStyle: "cards" },
  "lotus-vietnamese": { layout: "arch", photoTreatment: "framed", countdownStyle: "rings", eventStyle: "steps" },
  "imperial-red": { layout: "arch", photoTreatment: "framed", countdownStyle: "cards", eventStyle: "steps" },
  "ivory-gold": { layout: "portrait", photoTreatment: "full-bleed", countdownStyle: "rings", eventStyle: "agenda" },
  "lavender-dream": { layout: "story", photoTreatment: "collage", countdownStyle: "cards", eventStyle: "timeline" },
  "terracotta-sunset": { layout: "split", photoTreatment: "split", countdownStyle: "rings", eventStyle: "cards" },
  "pearl-minimal": { layout: "minimal", photoTreatment: "optional", countdownStyle: "minimal", eventStyle: "agenda" },
  "midnight-blue": { layout: "portrait", photoTreatment: "full-bleed", countdownStyle: "editorial", eventStyle: "timeline" },
  "tropical-palm": { layout: "story", photoTreatment: "collage", countdownStyle: "rings", eventStyle: "cards" },
  "cherry-blossom": { layout: "split", photoTreatment: "soft", countdownStyle: "cards", eventStyle: "timeline" },
  "rustic-kraft": { layout: "story", photoTreatment: "framed", countdownStyle: "cards", eventStyle: "steps" },
  "art-deco-emerald": { layout: "editorial", photoTreatment: "framed", countdownStyle: "editorial", eventStyle: "agenda" },
  "champagne-glow": { layout: "portrait", photoTreatment: "full-bleed", countdownStyle: "rings", eventStyle: "timeline" },
  "celestial-night": { layout: "portrait", photoTreatment: "full-bleed", countdownStyle: "editorial", eventStyle: "cards" },
  "coastal-sand": { layout: "split", photoTreatment: "split", countdownStyle: "minimal", eventStyle: "cards" },
  "tea-ceremony": { layout: "arch", photoTreatment: "framed", countdownStyle: "rings", eventStyle: "steps" },
  "monochrome-editorial": { layout: "editorial", photoTreatment: "full-bleed", countdownStyle: "editorial", eventStyle: "agenda" },
  "peach-bloom": { layout: "story", photoTreatment: "collage", countdownStyle: "cards", eventStyle: "timeline" },
  "heritage-indigo": { layout: "arch", photoTreatment: "framed", countdownStyle: "rings", eventStyle: "steps" },
  "botanical-white": { layout: "minimal", photoTreatment: "soft", countdownStyle: "minimal", eventStyle: "cards" },
  "saigon-sunrise": { layout: "editorial", photoTreatment: "full-bleed", countdownStyle: "cards", eventStyle: "agenda" },
  "polaroid-memories": { layout: "story", photoTreatment: "collage", countdownStyle: "cards", eventStyle: "timeline" },
  "han-river-blue": { layout: "split", photoTreatment: "split", countdownStyle: "minimal", eventStyle: "cards" },
  "rose-garden-frame": { layout: "arch", photoTreatment: "framed", countdownStyle: "rings", eventStyle: "steps" },
  "cinematic-veil": { layout: "portrait", photoTreatment: "full-bleed", countdownStyle: "editorial", eventStyle: "agenda" },
  "provence-blue": { layout: "story", photoTreatment: "collage", countdownStyle: "rings", eventStyle: "cards" },
  "newspaper-love": { layout: "editorial", photoTreatment: "full-bleed", countdownStyle: "minimal", eventStyle: "agenda" },
  "sunset-film": { layout: "split", photoTreatment: "soft", countdownStyle: "cards", eventStyle: "timeline" },
  "dragon-phoenix": { layout: "arch", photoTreatment: "framed", countdownStyle: "rings", eventStyle: "steps" },
  "museum-ivory": { layout: "minimal", photoTreatment: "optional", countdownStyle: "minimal", eventStyle: "agenda" },
  "winter-silver": { layout: "portrait", photoTreatment: "framed", countdownStyle: "editorial", eventStyle: "cards" },
  "cottage-floral": { layout: "story", photoTreatment: "collage", countdownStyle: "cards", eventStyle: "timeline" },
};

export const INVITATION_TEMPLATES = BASE_INVITATION_TEMPLATES.map((template) => ({
  ...template,
  ...TEMPLATE_EXPERIENCE[template.key],
}));

export const INVITATION_TEMPLATE_KEYS = INVITATION_TEMPLATES.map((template) => template.key);
export const INVITATION_TEMPLATE_KEY_SET = new Set<string>(INVITATION_TEMPLATE_KEYS);

export const DEFAULT_SECTION_ORDER = ["hero", "family", "story", "gallery", "countdown", "events", "gift", "footer"];
export const VALID_SECTION_KEYS = new Set(DEFAULT_SECTION_ORDER);
export const VALID_FONT_KEYS = new Set(["elegant-serif", "romantic-serif", "editorial-serif", "heritage-serif", "minimal-serif", "display-serif", "clean-sans", "modern-sans", "humanist-sans", "soft-sans"]);
