CREATE TYPE "SupportTicketStatus" AS ENUM ('OPEN','IN_PROGRESS','WAITING_CUSTOMER','RESOLVED','CLOSED');
CREATE TYPE "SupportTicketPriority" AS ENUM ('LOW','NORMAL','HIGH','URGENT');
CREATE TYPE "DomainStatus" AS ENUM ('PENDING_DNS','VERIFYING','VERIFIED','ACTIVE','FAILED','DISABLED');
CREATE TABLE "GrowthEvent" ("id" TEXT NOT NULL,"userId" TEXT,"weddingId" TEXT,"sessionId" TEXT,"eventName" TEXT NOT NULL,"source" TEXT,"campaign" TEXT,"properties" JSONB,"occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "GrowthEvent_pkey" PRIMARY KEY ("id"));
CREATE INDEX "GrowthEvent_eventName_occurredAt_idx" ON "GrowthEvent"("eventName","occurredAt");
CREATE INDEX "GrowthEvent_userId_occurredAt_idx" ON "GrowthEvent"("userId","occurredAt");
CREATE INDEX "GrowthEvent_weddingId_occurredAt_idx" ON "GrowthEvent"("weddingId","occurredAt");
CREATE TABLE "ReferralCode" ("id" TEXT NOT NULL,"ownerUserId" TEXT NOT NULL,"code" TEXT NOT NULL,"label" TEXT,"active" BOOLEAN NOT NULL DEFAULT true,"visitCount" INTEGER NOT NULL DEFAULT 0,"signupCount" INTEGER NOT NULL DEFAULT 0,"conversionCount" INTEGER NOT NULL DEFAULT 0,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ReferralCode_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "ReferralCode_code_key" ON "ReferralCode"("code");
CREATE INDEX "ReferralCode_ownerUserId_active_idx" ON "ReferralCode"("ownerUserId","active");
CREATE TABLE "ReferralAttribution" ("id" TEXT NOT NULL,"referralCodeId" TEXT NOT NULL,"referredUserId" TEXT,"sessionId" TEXT,"source" TEXT,"attributedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"convertedAt" TIMESTAMP(3),CONSTRAINT "ReferralAttribution_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "ReferralAttribution_referredUserId_key" ON "ReferralAttribution"("referredUserId");
CREATE INDEX "ReferralAttribution_referralCodeId_attributedAt_idx" ON "ReferralAttribution"("referralCodeId","attributedAt");
CREATE TABLE "OnboardingProgress" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"steps" JSONB NOT NULL,"dismissed" BOOLEAN NOT NULL DEFAULT false,"completedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "OnboardingProgress_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "OnboardingProgress_userId_key" ON "OnboardingProgress"("userId");
CREATE TABLE "SupportTicket" ("id" TEXT NOT NULL,"userId" TEXT,"email" TEXT NOT NULL,"subject" TEXT NOT NULL,"category" TEXT NOT NULL DEFAULT 'GENERAL',"priority" "SupportTicketPriority" NOT NULL DEFAULT 'NORMAL',"status" "SupportTicketStatus" NOT NULL DEFAULT 'OPEN',"message" TEXT NOT NULL,"resolution" TEXT,"assignedTo" TEXT,"firstResponseAt" TIMESTAMP(3),"resolvedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "SupportTicket_pkey" PRIMARY KEY ("id"));
CREATE INDEX "SupportTicket_status_priority_createdAt_idx" ON "SupportTicket"("status","priority","createdAt");
CREATE INDEX "SupportTicket_userId_createdAt_idx" ON "SupportTicket"("userId","createdAt");
CREATE TABLE "CustomDomain" ("id" TEXT NOT NULL,"weddingId" TEXT NOT NULL,"requestedById" TEXT NOT NULL,"hostname" TEXT NOT NULL,"status" "DomainStatus" NOT NULL DEFAULT 'PENDING_DNS',"verificationToken" TEXT NOT NULL,"dnsTarget" TEXT NOT NULL,"lastCheckedAt" TIMESTAMP(3),"verifiedAt" TIMESTAMP(3),"activatedAt" TIMESTAMP(3),"failureReason" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "CustomDomain_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "CustomDomain_weddingId_key" ON "CustomDomain"("weddingId");
CREATE UNIQUE INDEX "CustomDomain_hostname_key" ON "CustomDomain"("hostname");
CREATE UNIQUE INDEX "CustomDomain_verificationToken_key" ON "CustomDomain"("verificationToken");
CREATE INDEX "CustomDomain_status_updatedAt_idx" ON "CustomDomain"("status","updatedAt");
