"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { AppShell } from "../../../components/app-shell";
import { AuthGate } from "../../../components/auth-gate";
import { useAuth } from "../../../components/auth-provider";
import { InlineErrorState, PageSkeleton, PermissionState } from "../../../components/ui";
import { toUiError, type UiError } from "../../../lib/api";
type Check = { id:string; code:string; category:string; title:string; description:string|null; owner:string|null; status:string; notes:string|null };
type Issue = { id:string; title:string; description:string; severity:string; status:string; area:string; assignee:string|null; createdAt:string };
type Announcement = { id:string; title:string; message:string; level:string; active:boolean; createdAt:string };
type Overview = { checklist:Check[]; issues:Issue[]; announcements:Announcement[]; metrics:{completion:number;blockers:number;totalChecklist:number;openIssues:number}; goLiveReady:boolean };
function PilotContent(){
 const {user,authRequest}=useAuth(); const [data,setData]=useState<Overview|null>(null); const [error,setError]=useState<UiError|null>(null); const [busy,setBusy]=useState(false); const [tab,setTab]=useState<"checklist"|"issues"|"announcements">("checklist");
 const [issue,setIssue]=useState({title:"",description:"",severity:"MEDIUM",area:"UI/UX"}); const [notice,setNotice]=useState({title:"",message:"",level:"INFO"});
 const load=useCallback(()=>authRequest<Overview>("/admin/pilot").then(setData),[authRequest]); useEffect(()=>{if(user&&["ADMIN","STAFF"].includes(user.role)) void load().catch(e=>setError(toUiError(e,"Không thể tải Pilot Center.")));},[load,user]);
 const groups=useMemo(()=>Object.entries((data?.checklist??[]).reduce<Record<string,Check[]>>((a,i)=>{(a[i.category]??=[]).push(i);return a;},{})),[data]);
 async function patch(path:string,body?:unknown){setBusy(true);setError(null);try{await authRequest(path,{method:"PATCH",body:body?JSON.stringify(body):undefined});await load();}catch(e){setError(toUiError(e,"Thao tác thất bại."));}finally{setBusy(false)}}
 async function submitIssue(e:FormEvent){e.preventDefault();setBusy(true);try{await authRequest("/admin/pilot/issues",{method:"POST",body:JSON.stringify(issue)});setIssue({title:"",description:"",severity:"MEDIUM",area:"UI/UX"});await load();}catch(e){setError(toUiError(e,"Không thể tạo issue."));}finally{setBusy(false)}}
 async function submitNotice(e:FormEvent){e.preventDefault();setBusy(true);try{await authRequest("/admin/pilot/announcements",{method:"POST",body:JSON.stringify(notice)});setNotice({title:"",message:"",level:"INFO"});await load();}catch(e){setError(toUiError(e,"Không thể tạo thông báo."));}finally{setBusy(false)}}
 if(!user||!["ADMIN","STAFF"].includes(user.role)) return <AppShell active="pilot"><div className="page-state-panel"><PermissionState description="Go-live Control Center chỉ dành cho Admin và Staff." /></div></AppShell>;
 if(!data&&!error) return <AppShell active="pilot"><PageSkeleton cards={3}/></AppShell>;
 return <AppShell active="pilot"><div className="page-heading pilot-heading"><div><p className="eyebrow">PILOT LAUNCH</p><h1>Go-live Control Center</h1><p>Checklist UAT, blocker, thông báo bảo trì và quyết định phát hành trong một màn hình.</p></div><div className={`go-live-badge ${data?.goLiveReady?"ready":"blocked"}`}><span>{data?.goLiveReady?"GO-LIVE READY":"CHƯA SẴN SÀNG"}</span><strong>{data?.metrics.completion??0}%</strong></div></div>
 {error?<InlineErrorState description={error.message} requestId={error.requestId} onRetry={()=>void load()}/>:null}<div className="pilot-kpis"><article><span>Hoàn thành</span><strong>{data?.metrics.completion??0}%</strong></article><article><span>Blocker High/Critical</span><strong>{data?.metrics.blockers??0}</strong></article><article><span>Issue đang mở</span><strong>{data?.metrics.openIssues??0}</strong></article><article><span>Checklist</span><strong>{data?.metrics.totalChecklist??0}</strong></article></div>
 <nav className="studio-tabs"><button className={tab==="checklist"?"active":""} onClick={()=>setTab("checklist")}>Go-live checklist</button><button className={tab==="issues"?"active":""} onClick={()=>setTab("issues")}>UAT issues</button><button className={tab==="announcements"?"active":""} onClick={()=>setTab("announcements")}>Thông báo</button></nav>
 {tab==="checklist"&&<div className="pilot-groups">{groups.map(([name,items])=><section className="panel" key={name}><h2>{name}</h2>{items.map(item=><article className="pilot-check" key={item.id}><div><code>{item.code}</code><strong>{item.title}</strong><p>{item.description}</p></div><select disabled={busy} value={item.status} onChange={e=>void patch(`/admin/pilot/checklist/${item.id}`,{status:e.target.value})}><option value="NOT_STARTED">Chưa bắt đầu</option><option value="IN_PROGRESS">Đang làm</option><option value="BLOCKED">Bị chặn</option><option value="PASSED">Đạt</option><option value="FAILED">Không đạt</option><option value="WAIVED">Chấp nhận ngoại lệ</option></select></article>)}</section>)}</div>}
 {tab==="issues"&&<div className="pilot-two"><form className="panel pilot-form" onSubmit={submitIssue}><h2>Ghi nhận UAT issue</h2><label>Tiêu đề<input required value={issue.title} onChange={e=>setIssue({...issue,title:e.target.value})}/></label><label>Mô tả<textarea required value={issue.description} onChange={e=>setIssue({...issue,description:e.target.value})}/></label><div className="form-grid"><label>Mức độ<select value={issue.severity} onChange={e=>setIssue({...issue,severity:e.target.value})}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label><label>Khu vực<input value={issue.area} onChange={e=>setIssue({...issue,area:e.target.value})}/></label></div><button className="btn btn-primary" disabled={busy}>Tạo issue</button></form><section className="panel"><h2>Danh sách issue</h2>{data?.issues.map(i=><article className="pilot-issue" key={i.id}><div><span className={`severity ${i.severity.toLowerCase()}`}>{i.severity}</span><strong>{i.title}</strong><p>{i.area} · {i.status}</p></div><select value={i.status} disabled={busy} onChange={e=>void patch(`/admin/pilot/issues/${i.id}`,{status:e.target.value})}><option>OPEN</option><option>INVESTIGATING</option><option>FIXED</option><option>VERIFIED</option><option>CLOSED</option></select></article>)}</section></div>}
 {tab==="announcements"&&<div className="pilot-two"><form className="panel pilot-form" onSubmit={submitNotice}><h2>Thông báo hệ thống</h2><label>Tiêu đề<input required value={notice.title} onChange={e=>setNotice({...notice,title:e.target.value})}/></label><label>Nội dung<textarea required value={notice.message} onChange={e=>setNotice({...notice,message:e.target.value})}/></label><label>Mức độ<select value={notice.level} onChange={e=>setNotice({...notice,level:e.target.value})}><option>INFO</option><option>MAINTENANCE</option><option>WARNING</option><option>RESOLVED</option></select></label><button className="btn btn-primary" disabled={busy}>Đăng thông báo</button></form><section className="panel"><h2>Thông báo gần đây</h2>{data?.announcements.map(a=><article className="pilot-issue" key={a.id}><div><span className="severity low">{a.level}</span><strong>{a.title}</strong><p>{a.message}</p></div><button className="btn btn-secondary" disabled={busy} onClick={()=>void patch(`/admin/pilot/announcements/${a.id}/toggle`)}>{a.active?"Tắt":"Bật"}</button></article>)}</section></div>}
 </AppShell>;
}
export default function PilotPage(){return <AuthGate><PilotContent/></AuthGate>}
